# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Magpie Embedded
email: magpieembedded@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Magpie Embedded Limited is a software based consultancy, with experience in a wide range of systems and devices. Registered No. 12711043
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://yourdomain.com" # the base hostname & protocol for your sit

# Build settings
markdown: kramdown

theme: minima

port: 4001
